import = ["gruvbox.yml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrains Mono"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "K"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "W"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Super"

[scrolling]
history = 0

[window.dimensions]
columns = 160
lines = 48
